### PR TITLE
Cleanup jobs that failed due to backoffLimitExceeded

### PR DESCRIPTION
**Pull request by sunghoonkim-wk**
The README states:
>Kube-janitor aims to cleanup only after your job has finished regardless of failure or success.

but it doesn't seem to actually clean up failed jobs.
We'd like to clean up jobs that hit the backoff limit.

- Edits `ExpiredJobs` to also clean up jobs that fail with `backoffLimitExceeded`

**Testing results:**
- Installed a job with a bad image in minikube with a low backoffLimit:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: failure-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: failure
        image: alpine:3.7
        command: ["blahblah"]
      restartPolicy: "Never"
```
- Helm installed kube-janitor with a low expiration time:
```
$ helm install ./kube-janitor/ --set image.tag="local" --set image.repository="kube-janitor" --set image.pullPolicy="Never" --set kubejanitor.expiration=5 --name kube-janitor
```
- confirmed failed job was removed

### CODE REVIEW

**Comment by theMagicalKarp** [comment]
> completionTime: Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. 

🤦
After this PR we will have to circle back and see what other failure scenarios aren't setting the `completionTime`.

**Comment by theMagicalKarp** [comment]
+1

**Comment by sunghoonkim-wk** [comment]
>After this PR we will have to circle back and see what other failure scenarios aren't setting the completionTime.

I think `completionTime` is only set for successful jobs. See: https://github.com/kubernetes/kubernetes/issues/68712

**Comment by theMagicalKarp** [comment]
@SimKev2

**Comment by SimKev2** [comment]
With this branch checked out and built
```console
$ helm install kube-janitor --set image.tag="local" --set image.pullPolicy="Never" --set kubejanitor.expiration=1
NAME:   jazzy-ferret
LAST DEPLOYED: Wed Mar 13 12:53:38 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                       AGE
jazzy-ferret-kube-janitor  0s

==> v1/ServiceAccount
NAME                       SECRETS  AGE
jazzy-ferret-kube-janitor  1        0s

==> v1beta1/ClusterRoleBinding
NAME                       AGE
jazzy-ferret-kube-janitor  0s

==> v1beta1/CronJob
NAME                       SCHEDULE     SUSPEND  ACTIVE  LAST SCHEDULE  AGE
jazzy-ferret-kube-janitor  */1 * * * *  False    0       <none>         0s
```

Creating the job, it was successfully cleaned up even though it was in backoff state
```console
$ cat job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: testcontainer
        image: debian:jessie-slim
        command: ["exit", "1"]
      restartPolicy: "Never"
$ kubectl create -f job.yaml
job.batch/testjob created
$ kubectl describe job testjob
Name:           testjob
Namespace:      default
Selector:       controller-uid=8cfb9ea1-45b8-11e9-aaa4-0800271ed8f8
Labels:         controller-uid=8cfb9ea1-45b8-11e9-aaa4-0800271ed8f8
                job-name=testjob
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Wed, 13 Mar 2019 12:50:55 -0500
Pods Statuses:  0 Running / 0 Succeeded / 1 Failed
Pod Template:
  Labels:  controller-uid=8cfb9ea1-45b8-11e9-aaa4-0800271ed8f8
           job-name=testjob
  Containers:
   testcontainer:
    Image:      debian:jessie-slim
    Port:       <none>
    Host Port:  <none>
    Command:
      exit
      1
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      49s   job-controller  Created pod: testjob-l6lw6
  Warning  BackoffLimitExceeded  40s   job-controller  Job has reach the specified backoff limit
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY     STATUS               RESTARTS   AGE
default       testjob-l6lw6                            0/1       ContainerCannotRun   0          1m
...
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                         READY     STATUS      RESTARTS   AGE
default       jazzy-ferret-kube-janitor-1552499640-5tfnj   0/1       Completed   0          5s
```

QA +1

**Pull request merged**
